"""empty message

Revision ID: 00bdbdf8533e
Revises: 
Create Date: 2018-09-08 09:12:35.081789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00bdbdf8533e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('areas', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'areas', ['code'])
    op.add_column('governates', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('governates', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'governates', ['code'])
    op.add_column('villages', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('villages', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'villages', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'villages', type_='unique')
    op.drop_column('villages', 'updated_at')
    op.drop_column('villages', 'created_at')
    op.drop_constraint(None, 'governates', type_='unique')
    op.drop_column('governates', 'updated_at')
    op.drop_column('governates', 'created_at')
    op.drop_constraint(None, 'areas', type_='unique')
    op.drop_column('areas', 'updated_at')
    op.drop_column('areas', 'created_at')
    # ### end Alembic commands ###
